### ISSUE TITLE
Algorithmus

### ISSUE THREAD

**Issue by Edgxxar** [TUDa-BP-11/opendiabetes-uam-heuristik#8]
- [x] "korrekte" Berechnung von Carbs
- [x] Strategie Pattern für Algo und Dataprovider Modularität
- [x] Verwendung von JSAP für Argumente
- [x] Plotten mit Pyhton-Matplotlib
- [x] Sinnvolle Exceptions und Fehler Meldungen

**Comment by avrpm** [comment]
Daten werden geplottet
